# Generated by Django 4.2.10 on 2024-03-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_file_name', models.CharField(max_length=200)),
                ('header_name', models.CharField(max_length=200)),
                ('modified_name', models.CharField(max_length=200)),
                ('is_primary_key', models.BooleanField(default=False)),
            ],
        ),
    ]
