# Generated by Django 4.2.10 on 2024-03-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='modified_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
