# Generated by Django 4.2.10 on 2024-03-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_modified_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forminfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_name_alias', models.CharField(blank=True, max_length=200)),
                ('datatype', models.CharField(max_length=200)),
                ('header_name', models.CharField(max_length=200)),
                ('is_primary_key', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Queryinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_name_alias', models.CharField(blank=True, max_length=200)),
                ('query', models.CharField(max_length=4000)),
            ],
        ),
    ]
