# Generated by Django 4.2.10 on 2024-03-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_forminfo_queryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='forminfo',
            name='client_file_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
